package com.pj.service.impl.exe;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class NewJFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private javax.swing.JButton decodeButton;
	private javax.swing.JButton encryptionButton;
	private javax.swing.JTextField inputText;
	private javax.swing.JTextField outText;
	
	public static final String ALGORITHM = "AES";

	/**
	 * Creates new form NewJFrame
	 */
	public NewJFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		encryptionButton = new javax.swing.JButton();
		decodeButton = new javax.swing.JButton();
		inputText = new javax.swing.JTextField();
		outText = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		encryptionButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
		encryptionButton.setText("加密");

		decodeButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
		decodeButton.setText("解密");

		inputText.setToolTipText("");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(68, 68, 68).addComponent(encryptionButton)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109,
										Short.MAX_VALUE)
								.addComponent(decodeButton).addGap(93, 93, 93))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addContainerGap().addComponent(inputText)
										.addContainerGap())
						.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(outText)
								.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap(15, Short.MAX_VALUE)
				.addComponent(inputText, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(encryptionButton).addComponent(decodeButton,
								javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(outText, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE).addGap(18, 18, 18)));

		outText.getAccessibleContext().setAccessibleDescription("");

		getAccessibleContext().setAccessibleDescription("");
		encryptionButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				
				outText.setText(inputText.getText());
			}
		});
		pack();
	}// </editor-fold>

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		new NewJFrame();
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new NewJFrame().setVisible(true);
			}
		});
	}

}